'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="FDA_FOOD_ANGULAR")>  _
Partial Public Class LINQ_FOODDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertMAIN_DATA_DRIVE(instance As MAIN_DATA_DRIVE)
    End Sub
  Partial Private Sub UpdateMAIN_DATA_DRIVE(instance As MAIN_DATA_DRIVE)
    End Sub
  Partial Private Sub DeleteMAIN_DATA_DRIVE(instance As MAIN_DATA_DRIVE)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.ManageFile.My.MySettings.Default.FDA_FOOD_ANGULARConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property MAIN_DATA_DRIVEs() As System.Data.Linq.Table(Of MAIN_DATA_DRIVE)
		Get
			Return Me.GetTable(Of MAIN_DATA_DRIVE)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.MAIN_DATA_DRIVE")>  _
Partial Public Class MAIN_DATA_DRIVE
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _IDA As Integer
	
	Private _PROCESS_ID As String
	
	Private _TR_ID As String
	
	Private _TRANSACTION_NO As String
	
	Private _FDPDTNO As String
	
	Private _STATUS_ID As String
	
	Private _CREATE_ID As String
	
	Private _CREATE_DATE As System.Nullable(Of Date)
	
	Private _UPDATE_DATE As System.Nullable(Of Date)
	
	Private _PVNCD As String
	
	Private _RCVNO As String
	
	Private _RCVDATE As System.Nullable(Of Date)
	
	Private _CITIZEN_ID As String
	
	Private _CITIZEN_AUTHORIZE_ID As String
	
	Private _LOCATION_ID As String
	
	Private _STAFF_ID As String
	
	Private _FDTYPECD As String
	
	Private _AUTO As String
	
	Private _REF_FDPDTNO As String
	
	Private _REF_FDPDTNO2 As String
	
	Private _REQUEST_EXP_DATE As System.Nullable(Of Date)
	
	Private _SYSTEM As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIDAChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDAChanged()
    End Sub
    Partial Private Sub OnPROCESS_IDChanging(value As String)
    End Sub
    Partial Private Sub OnPROCESS_IDChanged()
    End Sub
    Partial Private Sub OnTR_IDChanging(value As String)
    End Sub
    Partial Private Sub OnTR_IDChanged()
    End Sub
    Partial Private Sub OnTRANSACTION_NOChanging(value As String)
    End Sub
    Partial Private Sub OnTRANSACTION_NOChanged()
    End Sub
    Partial Private Sub OnFDPDTNOChanging(value As String)
    End Sub
    Partial Private Sub OnFDPDTNOChanged()
    End Sub
    Partial Private Sub OnSTATUS_IDChanging(value As String)
    End Sub
    Partial Private Sub OnSTATUS_IDChanged()
    End Sub
    Partial Private Sub OnCREATE_IDChanging(value As String)
    End Sub
    Partial Private Sub OnCREATE_IDChanged()
    End Sub
    Partial Private Sub OnCREATE_DATEChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnCREATE_DATEChanged()
    End Sub
    Partial Private Sub OnUPDATE_DATEChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnUPDATE_DATEChanged()
    End Sub
    Partial Private Sub OnPVNCDChanging(value As String)
    End Sub
    Partial Private Sub OnPVNCDChanged()
    End Sub
    Partial Private Sub OnRCVNOChanging(value As String)
    End Sub
    Partial Private Sub OnRCVNOChanged()
    End Sub
    Partial Private Sub OnRCVDATEChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnRCVDATEChanged()
    End Sub
    Partial Private Sub OnCITIZEN_IDChanging(value As String)
    End Sub
    Partial Private Sub OnCITIZEN_IDChanged()
    End Sub
    Partial Private Sub OnCITIZEN_AUTHORIZE_IDChanging(value As String)
    End Sub
    Partial Private Sub OnCITIZEN_AUTHORIZE_IDChanged()
    End Sub
    Partial Private Sub OnLOCATION_IDChanging(value As String)
    End Sub
    Partial Private Sub OnLOCATION_IDChanged()
    End Sub
    Partial Private Sub OnSTAFF_IDChanging(value As String)
    End Sub
    Partial Private Sub OnSTAFF_IDChanged()
    End Sub
    Partial Private Sub OnFDTYPECDChanging(value As String)
    End Sub
    Partial Private Sub OnFDTYPECDChanged()
    End Sub
    Partial Private Sub OnAUTOChanging(value As String)
    End Sub
    Partial Private Sub OnAUTOChanged()
    End Sub
    Partial Private Sub OnREF_FDPDTNOChanging(value As String)
    End Sub
    Partial Private Sub OnREF_FDPDTNOChanged()
    End Sub
    Partial Private Sub OnREF_FDPDTNO2Changing(value As String)
    End Sub
    Partial Private Sub OnREF_FDPDTNO2Changed()
    End Sub
    Partial Private Sub OnREQUEST_EXP_DATEChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnREQUEST_EXP_DATEChanged()
    End Sub
    Partial Private Sub OnSYSTEMChanging(value As String)
    End Sub
    Partial Private Sub OnSYSTEMChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDA", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property IDA() As Integer
		Get
			Return Me._IDA
		End Get
		Set
			If ((Me._IDA = value)  _
						= false) Then
				Me.OnIDAChanging(value)
				Me.SendPropertyChanging
				Me._IDA = value
				Me.SendPropertyChanged("IDA")
				Me.OnIDAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PROCESS_ID", DbType:="NVarChar(10)")>  _
	Public Property PROCESS_ID() As String
		Get
			Return Me._PROCESS_ID
		End Get
		Set
			If (String.Equals(Me._PROCESS_ID, value) = false) Then
				Me.OnPROCESS_IDChanging(value)
				Me.SendPropertyChanging
				Me._PROCESS_ID = value
				Me.SendPropertyChanged("PROCESS_ID")
				Me.OnPROCESS_IDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TR_ID", DbType:="NVarChar(10)")>  _
	Public Property TR_ID() As String
		Get
			Return Me._TR_ID
		End Get
		Set
			If (String.Equals(Me._TR_ID, value) = false) Then
				Me.OnTR_IDChanging(value)
				Me.SendPropertyChanging
				Me._TR_ID = value
				Me.SendPropertyChanged("TR_ID")
				Me.OnTR_IDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TRANSACTION_NO", DbType:="NVarChar(30)")>  _
	Public Property TRANSACTION_NO() As String
		Get
			Return Me._TRANSACTION_NO
		End Get
		Set
			If (String.Equals(Me._TRANSACTION_NO, value) = false) Then
				Me.OnTRANSACTION_NOChanging(value)
				Me.SendPropertyChanging
				Me._TRANSACTION_NO = value
				Me.SendPropertyChanged("TRANSACTION_NO")
				Me.OnTRANSACTION_NOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FDPDTNO", DbType:="NVarChar(13)")>  _
	Public Property FDPDTNO() As String
		Get
			Return Me._FDPDTNO
		End Get
		Set
			If (String.Equals(Me._FDPDTNO, value) = false) Then
				Me.OnFDPDTNOChanging(value)
				Me.SendPropertyChanging
				Me._FDPDTNO = value
				Me.SendPropertyChanged("FDPDTNO")
				Me.OnFDPDTNOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_STATUS_ID", DbType:="NVarChar(10)")>  _
	Public Property STATUS_ID() As String
		Get
			Return Me._STATUS_ID
		End Get
		Set
			If (String.Equals(Me._STATUS_ID, value) = false) Then
				Me.OnSTATUS_IDChanging(value)
				Me.SendPropertyChanging
				Me._STATUS_ID = value
				Me.SendPropertyChanged("STATUS_ID")
				Me.OnSTATUS_IDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CREATE_ID", DbType:="NVarChar(20)")>  _
	Public Property CREATE_ID() As String
		Get
			Return Me._CREATE_ID
		End Get
		Set
			If (String.Equals(Me._CREATE_ID, value) = false) Then
				Me.OnCREATE_IDChanging(value)
				Me.SendPropertyChanging
				Me._CREATE_ID = value
				Me.SendPropertyChanged("CREATE_ID")
				Me.OnCREATE_IDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CREATE_DATE", DbType:="DateTime")>  _
	Public Property CREATE_DATE() As System.Nullable(Of Date)
		Get
			Return Me._CREATE_DATE
		End Get
		Set
			If (Me._CREATE_DATE.Equals(value) = false) Then
				Me.OnCREATE_DATEChanging(value)
				Me.SendPropertyChanging
				Me._CREATE_DATE = value
				Me.SendPropertyChanged("CREATE_DATE")
				Me.OnCREATE_DATEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_UPDATE_DATE", DbType:="DateTime")>  _
	Public Property UPDATE_DATE() As System.Nullable(Of Date)
		Get
			Return Me._UPDATE_DATE
		End Get
		Set
			If (Me._UPDATE_DATE.Equals(value) = false) Then
				Me.OnUPDATE_DATEChanging(value)
				Me.SendPropertyChanging
				Me._UPDATE_DATE = value
				Me.SendPropertyChanged("UPDATE_DATE")
				Me.OnUPDATE_DATEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PVNCD", DbType:="NVarChar(10)")>  _
	Public Property PVNCD() As String
		Get
			Return Me._PVNCD
		End Get
		Set
			If (String.Equals(Me._PVNCD, value) = false) Then
				Me.OnPVNCDChanging(value)
				Me.SendPropertyChanging
				Me._PVNCD = value
				Me.SendPropertyChanged("PVNCD")
				Me.OnPVNCDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RCVNO", DbType:="NVarChar(10)")>  _
	Public Property RCVNO() As String
		Get
			Return Me._RCVNO
		End Get
		Set
			If (String.Equals(Me._RCVNO, value) = false) Then
				Me.OnRCVNOChanging(value)
				Me.SendPropertyChanging
				Me._RCVNO = value
				Me.SendPropertyChanged("RCVNO")
				Me.OnRCVNOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RCVDATE", DbType:="DateTime")>  _
	Public Property RCVDATE() As System.Nullable(Of Date)
		Get
			Return Me._RCVDATE
		End Get
		Set
			If (Me._RCVDATE.Equals(value) = false) Then
				Me.OnRCVDATEChanging(value)
				Me.SendPropertyChanging
				Me._RCVDATE = value
				Me.SendPropertyChanged("RCVDATE")
				Me.OnRCVDATEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CITIZEN_ID", DbType:="NVarChar(20)")>  _
	Public Property CITIZEN_ID() As String
		Get
			Return Me._CITIZEN_ID
		End Get
		Set
			If (String.Equals(Me._CITIZEN_ID, value) = false) Then
				Me.OnCITIZEN_IDChanging(value)
				Me.SendPropertyChanging
				Me._CITIZEN_ID = value
				Me.SendPropertyChanged("CITIZEN_ID")
				Me.OnCITIZEN_IDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CITIZEN_AUTHORIZE_ID", DbType:="NVarChar(20)")>  _
	Public Property CITIZEN_AUTHORIZE_ID() As String
		Get
			Return Me._CITIZEN_AUTHORIZE_ID
		End Get
		Set
			If (String.Equals(Me._CITIZEN_AUTHORIZE_ID, value) = false) Then
				Me.OnCITIZEN_AUTHORIZE_IDChanging(value)
				Me.SendPropertyChanging
				Me._CITIZEN_AUTHORIZE_ID = value
				Me.SendPropertyChanged("CITIZEN_AUTHORIZE_ID")
				Me.OnCITIZEN_AUTHORIZE_IDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LOCATION_ID", DbType:="NVarChar(8)")>  _
	Public Property LOCATION_ID() As String
		Get
			Return Me._LOCATION_ID
		End Get
		Set
			If (String.Equals(Me._LOCATION_ID, value) = false) Then
				Me.OnLOCATION_IDChanging(value)
				Me.SendPropertyChanging
				Me._LOCATION_ID = value
				Me.SendPropertyChanged("LOCATION_ID")
				Me.OnLOCATION_IDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_STAFF_ID", DbType:="NVarChar(20)")>  _
	Public Property STAFF_ID() As String
		Get
			Return Me._STAFF_ID
		End Get
		Set
			If (String.Equals(Me._STAFF_ID, value) = false) Then
				Me.OnSTAFF_IDChanging(value)
				Me.SendPropertyChanging
				Me._STAFF_ID = value
				Me.SendPropertyChanged("STAFF_ID")
				Me.OnSTAFF_IDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FDTYPECD", DbType:="NVarChar(10)")>  _
	Public Property FDTYPECD() As String
		Get
			Return Me._FDTYPECD
		End Get
		Set
			If (String.Equals(Me._FDTYPECD, value) = false) Then
				Me.OnFDTYPECDChanging(value)
				Me.SendPropertyChanging
				Me._FDTYPECD = value
				Me.SendPropertyChanged("FDTYPECD")
				Me.OnFDTYPECDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="AUTO", Storage:="_AUTO", DbType:="NVarChar(4)")>  _
	Public Property [AUTO]() As String
		Get
			Return Me._AUTO
		End Get
		Set
			If (String.Equals(Me._AUTO, value) = false) Then
				Me.OnAUTOChanging(value)
				Me.SendPropertyChanging
				Me._AUTO = value
				Me.SendPropertyChanged("[AUTO]")
				Me.OnAUTOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_REF_FDPDTNO", DbType:="NVarChar(13)")>  _
	Public Property REF_FDPDTNO() As String
		Get
			Return Me._REF_FDPDTNO
		End Get
		Set
			If (String.Equals(Me._REF_FDPDTNO, value) = false) Then
				Me.OnREF_FDPDTNOChanging(value)
				Me.SendPropertyChanging
				Me._REF_FDPDTNO = value
				Me.SendPropertyChanged("REF_FDPDTNO")
				Me.OnREF_FDPDTNOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_REF_FDPDTNO2", DbType:="NVarChar(13)")>  _
	Public Property REF_FDPDTNO2() As String
		Get
			Return Me._REF_FDPDTNO2
		End Get
		Set
			If (String.Equals(Me._REF_FDPDTNO2, value) = false) Then
				Me.OnREF_FDPDTNO2Changing(value)
				Me.SendPropertyChanging
				Me._REF_FDPDTNO2 = value
				Me.SendPropertyChanged("REF_FDPDTNO2")
				Me.OnREF_FDPDTNO2Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_REQUEST_EXP_DATE", DbType:="DateTime")>  _
	Public Property REQUEST_EXP_DATE() As System.Nullable(Of Date)
		Get
			Return Me._REQUEST_EXP_DATE
		End Get
		Set
			If (Me._REQUEST_EXP_DATE.Equals(value) = false) Then
				Me.OnREQUEST_EXP_DATEChanging(value)
				Me.SendPropertyChanging
				Me._REQUEST_EXP_DATE = value
				Me.SendPropertyChanged("REQUEST_EXP_DATE")
				Me.OnREQUEST_EXP_DATEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SYSTEM", DbType:="NVarChar(20)")>  _
	Public Property SYSTEM() As String
		Get
			Return Me._SYSTEM
		End Get
		Set
			If (String.Equals(Me._SYSTEM, value) = false) Then
				Me.OnSYSTEMChanging(value)
				Me.SendPropertyChanging
				Me._SYSTEM = value
				Me.SendPropertyChanged("SYSTEM")
				Me.OnSYSTEMChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
